version: "3"

networks:
  laravel:


services:
  php:
    container_name: phpmyadmin_container
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./src:/code
    networks:
      - laravel
  

  mysql:
    container_name: mysql_container
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel


  nginx:
    container_name: nginx_container
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./src:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel



