version: '3'

services:
  mysql_db:
    container_name: mysql_container
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql

  wordpress:
    depends_on:
      - mysql_db
    container_name: wordpress_container
    image: wordpress:latest
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "./:/var/www/html"

  phpmyadmin:
    depends_on:
      - mysql_db
    container_name: phpmyadmin_container
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "./:/var/www/html/phpmyadmin"

volumes:
  mysql: {} 