version: '3.7'

services:
  
  db:
    image: mariadb
    container_name: wp-demo
    restart: always

    volumes:
      - db_data:/var/lib/mysql
      - ./backups:/backups

    environment:
        MYSQL_DATABASE: wpdemo
        MYSQL_USER: radenfebri
        MYSQL_PASSWORD: Febri_2303
        MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        MYSQL_RANDOM_ROOT_PASSWORD: Ekafebriansah2303

  wordpress:
      image: wordpress:latest
      container_name: wp-demo1
      restart: always
      depends_on: ['db']
      ports: ['80:80']
      links: ['db:db']
      volumes:
        - './wp_data:/var/www/html'

      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_NAME: wpdemo
        WORDPRESS_DB_USER: radenfebri
        WORDPRESS_DB_PASSWORD: Febri_2303

        
volumes:
  db_data: {}
          